services:
  postgres:
    image: postgres:latest
    container_name: jarvis_db
    environment:
      POSTGRES_DB: jarvis_db
      POSTGRES_USER: jarvis
      POSTGRES_PASSWORD: jarvis
    ports:
      - "5431:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
