server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/jarvis_db
    username: jarvis
    password: jarvis
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
